
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaEntidad
{

using System;
    using System.Collections.Generic;
    
public partial class ExamenV
{

    public int Id { get; set; }

    public int IDExpediente { get; set; }

    public string NombreImagen { get; set; }

    public Nullable<System.DateTime> FechaQueSeRealizo { get; set; }

    public System.DateTime FechaIngresoBD { get; set; }

    public byte[] Imagen { get; set; }

    public string Notas { get; set; }

    public bool Activo { get; set; }

}

}
