
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaEntidad
{

using System;
    using System.Collections.Generic;
    
public partial class RecetaV
{

    public int Id { get; set; }

    public int IDExpediente { get; set; }

    public string Medicamento { get; set; }

    public string Indicacion { get; set; }

    public Nullable<System.DateTime> FechaPrescripcion { get; set; }

    public Nullable<bool> Activo { get; set; }

}

}
