//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecedentePersonal
    {
        public int Id { get; set; }
        public int IDPaciente { get; set; }
        public string Padecimiento { get; set; }
        public string EnfermedadCronica { get; set; }
        public string Alergias { get; set; }
        public string Cirugias { get; set; }
        public string Transfusion { get; set; }
        public string Hospitalizacion { get; set; }
        public string TipoVivienda { get; set; }
        public string HabitoHigiene { get; set; }
        public string HabitoAlimentacion { get; set; }
        public string DesarrolloSocial { get; set; }
        public bool Activo { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
