//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargarPacientesV
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Tipo_de_Sangre { get; set; }
        public System.DateTime F__Nacimiento { get; set; }
        public Nullable<System.DateTime> Ultima_Consulta { get; set; }
        public bool Activo { get; set; }
    }
}
