//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargarConsultaV
    {
        public int Id { get; set; }
        public string HistoriaActual { get; set; }
        public int IDExpediente { get; set; }
        public string Diagnostico { get; set; }
        public string Observaciones { get; set; }
        public string Tratamiento { get; set; }
        public Nullable<int> IDMedico { get; set; }
        public bool Activo { get; set; }
        public int IdSomatometria { get; set; }
        public int IDConsulta { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Estatura { get; set; }
        public Nullable<double> PerimetroCefalico { get; set; }
        public Nullable<double> PerimetroAbdominal { get; set; }
        public Nullable<double> PerimetroToracico { get; set; }
        public Nullable<int> FrecuenciaCardiaca { get; set; }
        public Nullable<int> FrecuenciaRespiratoria { get; set; }
        public Nullable<double> PresionSistolica { get; set; }
        public Nullable<double> PresionDiastolica { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public string Exploratorio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
