//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargarInformacionFamiliarPersonalizadaV
    {
        public int Id { get; set; }
        public int IDPaciente { get; set; }
        public int IdHistoria { get; set; }
        public string Nombre { get; set; }
        public string Observacion { get; set; }
        public string Parentesco { get; set; }
        public string Paciente { get; set; }
    }
}
