//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargarInformacionFamiliarV
    {
        public int Id { get; set; }
        public int IdHistoria { get; set; }
        public string Nombre { get; set; }
        public int IDParentesco { get; set; }
        public string Parentesco { get; set; }
        public Nullable<int> IDGrupoSanguineo { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<int> TelContacto { get; set; }
        public string Anotaciones { get; set; }
        public string CondicionMedica { get; set; }
        public bool Activo { get; set; }
        public int IdPaciente { get; set; }
    }
}
