//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaV
    {
        public int Id { get; set; }
        public int IDExpediente { get; set; }
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
        public string HistoriaActual { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public Nullable<int> IDMedico { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
