//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class DosisVacunaV
    {
        public int Id { get; set; }
        public string NumeroDosis { get; set; }
        public int IDVacuna { get; set; }
        public Nullable<System.DateTime> FechaAplicacion { get; set; }
        public int IDExpediente { get; set; }
        public string Notas { get; set; }
        public Nullable<bool> enConsultorio { get; set; }
        public bool Activo { get; set; }
    }
}
