//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        public int Id { get; set; }
        public int IDExpediente { get; set; }
        public string NombreImagen { get; set; }
        public Nullable<System.DateTime> FechaQueSeRealizo { get; set; }
        public System.DateTime FechaIngresoBD { get; set; }
        public byte[] Imagen { get; set; }
        public string Notas { get; set; }
        public string Tipo { get; set; }
        public bool Activo { get; set; }
    
        public virtual Expediente Expediente { get; set; }
    }
}
