//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public Expediente()
        {
            this.Consulta = new HashSet<Consulta>();
            this.DosisVacuna = new HashSet<DosisVacuna>();
            this.Examen = new HashSet<Examen>();
            this.Receta = new HashSet<Receta>();
        }
    
        public int Id { get; set; }
        public int IDPaciente { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual ICollection<DosisVacuna> DosisVacuna { get; set; }
        public virtual ICollection<Examen> Examen { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
