//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoSanguineo
    {
        public GrupoSanguineo()
        {
            this.HistoriaClinicaFamiliar = new HashSet<HistoriaClinicaFamiliar>();
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int Id { get; set; }
        public string NombreGrupo { get; set; }
        public string Notas { get; set; }
    
        public virtual ICollection<HistoriaClinicaFamiliar> HistoriaClinicaFamiliar { get; set; }
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
