//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionNacimiento
    {
        public int Id { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Altura { get; set; }
        public Nullable<double> PerimetroCefalico { get; set; }
        public Nullable<bool> FueCesarea { get; set; }
        public Nullable<bool> Posicion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> CircularCordon { get; set; }
        public int IDPaciente { get; set; }
        public string MotivoCesarea { get; set; }
        public string ComplicacionEmbarazo { get; set; }
        public string EnfermedadEmbarazo { get; set; }
        public string MedicacionEmbarazo { get; set; }
        public Nullable<int> EdadGestacional { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
