//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPacientesV
    {
        public string Nombre1 { get; set; }
        public string Apellido1 { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string CiudadNacimiento { get; set; }
        public int IDGrupoSanguineo { get; set; }
        public int Id { get; set; }
        public int IDPaciente { get; set; }
        public int Expr1 { get; set; }
        public string NombreGrupo { get; set; }
    }
}
