//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.AntecedentePersonal = new HashSet<AntecedentePersonal>();
            this.Cita = new HashSet<Cita>();
            this.Expediente = new HashSet<Expediente>();
            this.InformacionFamiliar = new HashSet<InformacionFamiliar>();
            this.InformacionNacimiento = new HashSet<InformacionNacimiento>();
        }
    
        public int Id { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<bool> NacimientoHospital { get; set; }
        public string CiudadNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string Direccion { get; set; }
        public int IDGrupoSanguineo { get; set; }
        public bool EsNino { get; set; }
        public string NombrePadre { get; set; }
        public string CedulaPadre { get; set; }
        public string NombreMadre { get; set; }
        public string CedulaMadre { get; set; }
        public string Religion { get; set; }
        public string Notas { get; set; }
        public string Origen { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<AntecedentePersonal> AntecedentePersonal { get; set; }
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual ICollection<Expediente> Expediente { get; set; }
        public virtual GrupoSanguineo GrupoSanguineo { get; set; }
        public virtual ICollection<InformacionFamiliar> InformacionFamiliar { get; set; }
        public virtual ICollection<InformacionNacimiento> InformacionNacimiento { get; set; }
    }
}
