//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ConsultorioPediatricoBDEntities : DbContext
    {
        public ConsultorioPediatricoBDEntities()
            : base("name=ConsultorioPediatricoBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AntecedentePersonal> AntecedentePersonal { get; set; }
        public DbSet<Cita> Cita { get; set; }
        public DbSet<Consulta> Consulta { get; set; }
        public DbSet<DosisVacuna> DosisVacuna { get; set; }
        public DbSet<Examen> Examen { get; set; }
        public DbSet<Expediente> Expediente { get; set; }
        public DbSet<GrupoSanguineo> GrupoSanguineo { get; set; }
        public DbSet<HistoriaClinicaFamiliar> HistoriaClinicaFamiliar { get; set; }
        public DbSet<InformacionFamiliar> InformacionFamiliar { get; set; }
        public DbSet<InformacionNacimiento> InformacionNacimiento { get; set; }
        public DbSet<Medico> Medico { get; set; }
        public DbSet<Paciente> Paciente { get; set; }
        public DbSet<Parentesco> Parentesco { get; set; }
        public DbSet<Permiso> Permiso { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolPermiso> RolPermiso { get; set; }
        public DbSet<RolUsuario> RolUsuario { get; set; }
        public DbSet<Somatometria> Somatometria { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vacuna> Vacuna { get; set; }
        public DbSet<Receta> Receta { get; set; }
        public DbSet<AntecedentePersonalV> AntecedentePersonalV { get; set; }
        public DbSet<CargarConsultaV> CargarConsultaV { get; set; }
        public DbSet<CargarDosisVacunaPersonalizadaV> CargarDosisVacunaPersonalizadaV { get; set; }
        public DbSet<CargarExamenPersonalizadoV> CargarExamenPersonalizadoV { get; set; }
        public DbSet<CargarInformacionFamiliarPersonalizadaV> CargarInformacionFamiliarPersonalizadaV { get; set; }
        public DbSet<CargarInformacionFamiliarV> CargarInformacionFamiliarV { get; set; }
        public DbSet<CargarPacientesV> CargarPacientesV { get; set; }
        public DbSet<ConsultaV> ConsultaV { get; set; }
        public DbSet<DosisVacunaV> DosisVacunaV { get; set; }
        public DbSet<ExamenV> ExamenV { get; set; }
        public DbSet<ExpedienteV> ExpedienteV { get; set; }
        public DbSet<GrupoSanguineoV> GrupoSanguineoV { get; set; }
        public DbSet<HistoriaClinicaFamiliarV> HistoriaClinicaFamiliarV { get; set; }
        public DbSet<InformacionFamiliarV> InformacionFamiliarV { get; set; }
        public DbSet<InformacionNacimientoV> InformacionNacimientoV { get; set; }
        public DbSet<ListaPacientesV> ListaPacientesV { get; set; }
        public DbSet<PacienteV> PacienteV { get; set; }
        public DbSet<ParentescoV> ParentescoV { get; set; }
        public DbSet<RecetaV> RecetaV { get; set; }
        public DbSet<SomatometriaV> SomatometriaV { get; set; }
        public DbSet<UsuarioV> UsuarioV { get; set; }
        public DbSet<VacunaV> VacunaV { get; set; }
    
        public virtual int AntecedentePersonal_Actualizar(Nullable<int> id, Nullable<int> iDPaciente, string padecimiento, string alergias, string enfermedadCronica, string transfusion, string cirugias, string hospitalizacion, string tipoVivienda, string habitoHigiene, string habitoAlimentacion, string desarrolloSocial, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var padecimientoParameter = padecimiento != null ?
                new ObjectParameter("Padecimiento", padecimiento) :
                new ObjectParameter("Padecimiento", typeof(string));
    
            var alergiasParameter = alergias != null ?
                new ObjectParameter("Alergias", alergias) :
                new ObjectParameter("Alergias", typeof(string));
    
            var enfermedadCronicaParameter = enfermedadCronica != null ?
                new ObjectParameter("EnfermedadCronica", enfermedadCronica) :
                new ObjectParameter("EnfermedadCronica", typeof(string));
    
            var transfusionParameter = transfusion != null ?
                new ObjectParameter("Transfusion", transfusion) :
                new ObjectParameter("Transfusion", typeof(string));
    
            var cirugiasParameter = cirugias != null ?
                new ObjectParameter("Cirugias", cirugias) :
                new ObjectParameter("Cirugias", typeof(string));
    
            var hospitalizacionParameter = hospitalizacion != null ?
                new ObjectParameter("Hospitalizacion", hospitalizacion) :
                new ObjectParameter("Hospitalizacion", typeof(string));
    
            var tipoViviendaParameter = tipoVivienda != null ?
                new ObjectParameter("TipoVivienda", tipoVivienda) :
                new ObjectParameter("TipoVivienda", typeof(string));
    
            var habitoHigieneParameter = habitoHigiene != null ?
                new ObjectParameter("HabitoHigiene", habitoHigiene) :
                new ObjectParameter("HabitoHigiene", typeof(string));
    
            var habitoAlimentacionParameter = habitoAlimentacion != null ?
                new ObjectParameter("HabitoAlimentacion", habitoAlimentacion) :
                new ObjectParameter("HabitoAlimentacion", typeof(string));
    
            var desarrolloSocialParameter = desarrolloSocial != null ?
                new ObjectParameter("DesarrolloSocial", desarrolloSocial) :
                new ObjectParameter("DesarrolloSocial", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AntecedentePersonal_Actualizar", idParameter, iDPacienteParameter, padecimientoParameter, alergiasParameter, enfermedadCronicaParameter, transfusionParameter, cirugiasParameter, hospitalizacionParameter, tipoViviendaParameter, habitoHigieneParameter, habitoAlimentacionParameter, desarrolloSocialParameter, activoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> AntecedentePersonal_Insertar(Nullable<int> iDPaciente, string padecimiento, string alergias, string enfermedadCronica, string transfusion, string cirugias, string hospitalizacion, string tipoVivienda, string habitoHigiene, string habitoAlimentacion, string desarrolloSocial, Nullable<bool> activo)
        {
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var padecimientoParameter = padecimiento != null ?
                new ObjectParameter("Padecimiento", padecimiento) :
                new ObjectParameter("Padecimiento", typeof(string));
    
            var alergiasParameter = alergias != null ?
                new ObjectParameter("Alergias", alergias) :
                new ObjectParameter("Alergias", typeof(string));
    
            var enfermedadCronicaParameter = enfermedadCronica != null ?
                new ObjectParameter("EnfermedadCronica", enfermedadCronica) :
                new ObjectParameter("EnfermedadCronica", typeof(string));
    
            var transfusionParameter = transfusion != null ?
                new ObjectParameter("Transfusion", transfusion) :
                new ObjectParameter("Transfusion", typeof(string));
    
            var cirugiasParameter = cirugias != null ?
                new ObjectParameter("Cirugias", cirugias) :
                new ObjectParameter("Cirugias", typeof(string));
    
            var hospitalizacionParameter = hospitalizacion != null ?
                new ObjectParameter("Hospitalizacion", hospitalizacion) :
                new ObjectParameter("Hospitalizacion", typeof(string));
    
            var tipoViviendaParameter = tipoVivienda != null ?
                new ObjectParameter("TipoVivienda", tipoVivienda) :
                new ObjectParameter("TipoVivienda", typeof(string));
    
            var habitoHigieneParameter = habitoHigiene != null ?
                new ObjectParameter("HabitoHigiene", habitoHigiene) :
                new ObjectParameter("HabitoHigiene", typeof(string));
    
            var habitoAlimentacionParameter = habitoAlimentacion != null ?
                new ObjectParameter("HabitoAlimentacion", habitoAlimentacion) :
                new ObjectParameter("HabitoAlimentacion", typeof(string));
    
            var desarrolloSocialParameter = desarrolloSocial != null ?
                new ObjectParameter("DesarrolloSocial", desarrolloSocial) :
                new ObjectParameter("DesarrolloSocial", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("AntecedentePersonal_Insertar", iDPacienteParameter, padecimientoParameter, alergiasParameter, enfermedadCronicaParameter, transfusionParameter, cirugiasParameter, hospitalizacionParameter, tipoViviendaParameter, habitoHigieneParameter, habitoAlimentacionParameter, desarrolloSocialParameter, activoParameter);
        }
    
        public virtual int Consulta_Actualizar(Nullable<int> id, Nullable<int> iDExpediente, string diagnostico, string tratamiento, Nullable<System.DateTime> fecha, string observaciones, string historiaActual, Nullable<int> iDMedico, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            var diagnosticoParameter = diagnostico != null ?
                new ObjectParameter("Diagnostico", diagnostico) :
                new ObjectParameter("Diagnostico", typeof(string));
    
            var tratamientoParameter = tratamiento != null ?
                new ObjectParameter("Tratamiento", tratamiento) :
                new ObjectParameter("Tratamiento", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var historiaActualParameter = historiaActual != null ?
                new ObjectParameter("HistoriaActual", historiaActual) :
                new ObjectParameter("HistoriaActual", typeof(string));
    
            var iDMedicoParameter = iDMedico.HasValue ?
                new ObjectParameter("IDMedico", iDMedico) :
                new ObjectParameter("IDMedico", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Consulta_Actualizar", idParameter, iDExpedienteParameter, diagnosticoParameter, tratamientoParameter, fechaParameter, observacionesParameter, historiaActualParameter, iDMedicoParameter, activoParameter);
        }
    
        public virtual int Consulta_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Consulta_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Consulta_Insertar(Nullable<int> iDExpediente, string tratamiento, string diagnostico, Nullable<System.DateTime> fecha, string observaciones, string historiaActual, Nullable<int> iDMedico, Nullable<bool> activo)
        {
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            var tratamientoParameter = tratamiento != null ?
                new ObjectParameter("Tratamiento", tratamiento) :
                new ObjectParameter("Tratamiento", typeof(string));
    
            var diagnosticoParameter = diagnostico != null ?
                new ObjectParameter("Diagnostico", diagnostico) :
                new ObjectParameter("Diagnostico", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var historiaActualParameter = historiaActual != null ?
                new ObjectParameter("HistoriaActual", historiaActual) :
                new ObjectParameter("HistoriaActual", typeof(string));
    
            var iDMedicoParameter = iDMedico.HasValue ?
                new ObjectParameter("IDMedico", iDMedico) :
                new ObjectParameter("IDMedico", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Consulta_Insertar", iDExpedienteParameter, tratamientoParameter, diagnosticoParameter, fechaParameter, observacionesParameter, historiaActualParameter, iDMedicoParameter, activoParameter);
        }
    
        public virtual int DosisVacuna_Actualizar(Nullable<int> id, string numeroDosis, Nullable<int> iDVacuna, Nullable<System.DateTime> fechaAplicacion, Nullable<int> iDExpediente, string notas, Nullable<bool> enConsultorio, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var numeroDosisParameter = numeroDosis != null ?
                new ObjectParameter("NumeroDosis", numeroDosis) :
                new ObjectParameter("NumeroDosis", typeof(string));
    
            var iDVacunaParameter = iDVacuna.HasValue ?
                new ObjectParameter("IDVacuna", iDVacuna) :
                new ObjectParameter("IDVacuna", typeof(int));
    
            var fechaAplicacionParameter = fechaAplicacion.HasValue ?
                new ObjectParameter("FechaAplicacion", fechaAplicacion) :
                new ObjectParameter("FechaAplicacion", typeof(System.DateTime));
    
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var enConsultorioParameter = enConsultorio.HasValue ?
                new ObjectParameter("enConsultorio", enConsultorio) :
                new ObjectParameter("enConsultorio", typeof(bool));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DosisVacuna_Actualizar", idParameter, numeroDosisParameter, iDVacunaParameter, fechaAplicacionParameter, iDExpedienteParameter, notasParameter, enConsultorioParameter, activoParameter);
        }
    
        public virtual int DosisVacuna_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DosisVacuna_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> DosisVacuna_Insertar(string numeroDosis, Nullable<int> iDVacuna, Nullable<System.DateTime> fechaAplicacion, Nullable<int> iDExpediente, string notas, Nullable<bool> enConsultorio, Nullable<bool> activo)
        {
            var numeroDosisParameter = numeroDosis != null ?
                new ObjectParameter("NumeroDosis", numeroDosis) :
                new ObjectParameter("NumeroDosis", typeof(string));
    
            var iDVacunaParameter = iDVacuna.HasValue ?
                new ObjectParameter("IDVacuna", iDVacuna) :
                new ObjectParameter("IDVacuna", typeof(int));
    
            var fechaAplicacionParameter = fechaAplicacion.HasValue ?
                new ObjectParameter("FechaAplicacion", fechaAplicacion) :
                new ObjectParameter("FechaAplicacion", typeof(System.DateTime));
    
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var enConsultorioParameter = enConsultorio.HasValue ?
                new ObjectParameter("enConsultorio", enConsultorio) :
                new ObjectParameter("enConsultorio", typeof(bool));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("DosisVacuna_Insertar", numeroDosisParameter, iDVacunaParameter, fechaAplicacionParameter, iDExpedienteParameter, notasParameter, enConsultorioParameter, activoParameter);
        }
    
        public virtual int Examen_Actualizar(Nullable<int> id, Nullable<int> iDExpediente, string nombreImagen, Nullable<System.DateTime> fechaQueSeRealizo, Nullable<System.DateTime> fechaIngresoBD, byte[] imagen, string notas, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            var fechaQueSeRealizoParameter = fechaQueSeRealizo.HasValue ?
                new ObjectParameter("FechaQueSeRealizo", fechaQueSeRealizo) :
                new ObjectParameter("FechaQueSeRealizo", typeof(System.DateTime));
    
            var fechaIngresoBDParameter = fechaIngresoBD.HasValue ?
                new ObjectParameter("FechaIngresoBD", fechaIngresoBD) :
                new ObjectParameter("FechaIngresoBD", typeof(System.DateTime));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Examen_Actualizar", idParameter, iDExpedienteParameter, nombreImagenParameter, fechaQueSeRealizoParameter, fechaIngresoBDParameter, imagenParameter, notasParameter, activoParameter);
        }
    
        public virtual int Examen_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Examen_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Examen_Insertar(Nullable<int> iDExpediente, string nombreImagen, Nullable<System.DateTime> fechaQueSeRealizo, Nullable<System.DateTime> fechaIngresoBD, byte[] imagen, string notas, Nullable<bool> activo)
        {
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            var fechaQueSeRealizoParameter = fechaQueSeRealizo.HasValue ?
                new ObjectParameter("FechaQueSeRealizo", fechaQueSeRealizo) :
                new ObjectParameter("FechaQueSeRealizo", typeof(System.DateTime));
    
            var fechaIngresoBDParameter = fechaIngresoBD.HasValue ?
                new ObjectParameter("FechaIngresoBD", fechaIngresoBD) :
                new ObjectParameter("FechaIngresoBD", typeof(System.DateTime));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(byte[]));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Examen_Insertar", iDExpedienteParameter, nombreImagenParameter, fechaQueSeRealizoParameter, fechaIngresoBDParameter, imagenParameter, notasParameter, activoParameter);
        }
    
        public virtual int Expediente_Actualizar(Nullable<int> id, Nullable<int> iDPaciente, string descripcion, Nullable<System.DateTime> fechaCreacion, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Expediente_Actualizar", idParameter, iDPacienteParameter, descripcionParameter, fechaCreacionParameter, activoParameter);
        }
    
        public virtual int Expediente_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Expediente_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Expediente_Insertar(Nullable<int> iDPaciente, string descripcion, Nullable<System.DateTime> fechaCreacion, Nullable<bool> activo)
        {
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("FechaCreacion", fechaCreacion) :
                new ObjectParameter("FechaCreacion", typeof(System.DateTime));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Expediente_Insertar", iDPacienteParameter, descripcionParameter, fechaCreacionParameter, activoParameter);
        }
    
        public virtual int GrupoSanguineo_Actualizar(Nullable<int> id, string nombreGrupo, string notas)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreGrupoParameter = nombreGrupo != null ?
                new ObjectParameter("NombreGrupo", nombreGrupo) :
                new ObjectParameter("NombreGrupo", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GrupoSanguineo_Actualizar", idParameter, nombreGrupoParameter, notasParameter);
        }
    
        public virtual int GrupoSanguineo_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GrupoSanguineo_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> GrupoSanguineo_Insertar(string nombreGrupo, string notas)
        {
            var nombreGrupoParameter = nombreGrupo != null ?
                new ObjectParameter("NombreGrupo", nombreGrupo) :
                new ObjectParameter("NombreGrupo", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GrupoSanguineo_Insertar", nombreGrupoParameter, notasParameter);
        }
    
        public virtual int HistoriaClinicaFamiliar_Actualizar(Nullable<int> id, Nullable<int> iDInformacionFamiliar, string observacionesMedicas, Nullable<int> iDGrupoSanguineo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var iDInformacionFamiliarParameter = iDInformacionFamiliar.HasValue ?
                new ObjectParameter("IDInformacionFamiliar", iDInformacionFamiliar) :
                new ObjectParameter("IDInformacionFamiliar", typeof(int));
    
            var observacionesMedicasParameter = observacionesMedicas != null ?
                new ObjectParameter("ObservacionesMedicas", observacionesMedicas) :
                new ObjectParameter("ObservacionesMedicas", typeof(string));
    
            var iDGrupoSanguineoParameter = iDGrupoSanguineo.HasValue ?
                new ObjectParameter("IDGrupoSanguineo", iDGrupoSanguineo) :
                new ObjectParameter("IDGrupoSanguineo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HistoriaClinicaFamiliar_Actualizar", idParameter, iDInformacionFamiliarParameter, observacionesMedicasParameter, iDGrupoSanguineoParameter);
        }
    
        public virtual int HistoriaClinicaFamiliar_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HistoriaClinicaFamiliar_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> HistoriaClinicaFamiliar_Insertar(Nullable<int> iDInformacionFamiliar, string observacionesMedicas, Nullable<int> iDGrupoSanguineo)
        {
            var iDInformacionFamiliarParameter = iDInformacionFamiliar.HasValue ?
                new ObjectParameter("IDInformacionFamiliar", iDInformacionFamiliar) :
                new ObjectParameter("IDInformacionFamiliar", typeof(int));
    
            var observacionesMedicasParameter = observacionesMedicas != null ?
                new ObjectParameter("ObservacionesMedicas", observacionesMedicas) :
                new ObjectParameter("ObservacionesMedicas", typeof(string));
    
            var iDGrupoSanguineoParameter = iDGrupoSanguineo.HasValue ?
                new ObjectParameter("IDGrupoSanguineo", iDGrupoSanguineo) :
                new ObjectParameter("IDGrupoSanguineo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("HistoriaClinicaFamiliar_Insertar", iDInformacionFamiliarParameter, observacionesMedicasParameter, iDGrupoSanguineoParameter);
        }
    
        public virtual int InformacionFamiliar_Actualizar(Nullable<int> id, string nombre, Nullable<int> iDPaciente, Nullable<int> iDParentesco, Nullable<int> telContacto, string observaciones, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var iDParentescoParameter = iDParentesco.HasValue ?
                new ObjectParameter("IDParentesco", iDParentesco) :
                new ObjectParameter("IDParentesco", typeof(int));
    
            var telContactoParameter = telContacto.HasValue ?
                new ObjectParameter("TelContacto", telContacto) :
                new ObjectParameter("TelContacto", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InformacionFamiliar_Actualizar", idParameter, nombreParameter, iDPacienteParameter, iDParentescoParameter, telContactoParameter, observacionesParameter, activoParameter);
        }
    
        public virtual int InformacionFamiliar_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InformacionFamiliar_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> InformacionFamiliar_Insertar(string nombre, Nullable<int> iDPaciente, Nullable<int> iDParentesco, Nullable<int> telContacto, string observaciones, Nullable<bool> activo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var iDParentescoParameter = iDParentesco.HasValue ?
                new ObjectParameter("IDParentesco", iDParentesco) :
                new ObjectParameter("IDParentesco", typeof(int));
    
            var telContactoParameter = telContacto.HasValue ?
                new ObjectParameter("TelContacto", telContacto) :
                new ObjectParameter("TelContacto", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("InformacionFamiliar_Insertar", nombreParameter, iDPacienteParameter, iDParentescoParameter, telContactoParameter, observacionesParameter, activoParameter);
        }
    
        public virtual int InformacionNacimiento_Actualizar(Nullable<int> id, Nullable<double> peso, Nullable<double> altura, Nullable<double> perimetroCefalico, Nullable<bool> fueCesarea, Nullable<bool> posicion, string observaciones, Nullable<bool> circularCordon, Nullable<int> iDPaciente, string motivoCesarea, string enfermedadEmbarazo, string complicacionEmbarazo, string medicacionEmbarazo, Nullable<int> edadGestacional)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(double));
    
            var alturaParameter = altura.HasValue ?
                new ObjectParameter("Altura", altura) :
                new ObjectParameter("Altura", typeof(double));
    
            var perimetroCefalicoParameter = perimetroCefalico.HasValue ?
                new ObjectParameter("PerimetroCefalico", perimetroCefalico) :
                new ObjectParameter("PerimetroCefalico", typeof(double));
    
            var fueCesareaParameter = fueCesarea.HasValue ?
                new ObjectParameter("FueCesarea", fueCesarea) :
                new ObjectParameter("FueCesarea", typeof(bool));
    
            var posicionParameter = posicion.HasValue ?
                new ObjectParameter("Posicion", posicion) :
                new ObjectParameter("Posicion", typeof(bool));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var circularCordonParameter = circularCordon.HasValue ?
                new ObjectParameter("CircularCordon", circularCordon) :
                new ObjectParameter("CircularCordon", typeof(bool));
    
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var motivoCesareaParameter = motivoCesarea != null ?
                new ObjectParameter("MotivoCesarea", motivoCesarea) :
                new ObjectParameter("MotivoCesarea", typeof(string));
    
            var enfermedadEmbarazoParameter = enfermedadEmbarazo != null ?
                new ObjectParameter("EnfermedadEmbarazo", enfermedadEmbarazo) :
                new ObjectParameter("EnfermedadEmbarazo", typeof(string));
    
            var complicacionEmbarazoParameter = complicacionEmbarazo != null ?
                new ObjectParameter("ComplicacionEmbarazo", complicacionEmbarazo) :
                new ObjectParameter("ComplicacionEmbarazo", typeof(string));
    
            var medicacionEmbarazoParameter = medicacionEmbarazo != null ?
                new ObjectParameter("MedicacionEmbarazo", medicacionEmbarazo) :
                new ObjectParameter("MedicacionEmbarazo", typeof(string));
    
            var edadGestacionalParameter = edadGestacional.HasValue ?
                new ObjectParameter("EdadGestacional", edadGestacional) :
                new ObjectParameter("EdadGestacional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InformacionNacimiento_Actualizar", idParameter, pesoParameter, alturaParameter, perimetroCefalicoParameter, fueCesareaParameter, posicionParameter, observacionesParameter, circularCordonParameter, iDPacienteParameter, motivoCesareaParameter, enfermedadEmbarazoParameter, complicacionEmbarazoParameter, medicacionEmbarazoParameter, edadGestacionalParameter);
        }
    
        public virtual int InformacionNacimiento_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InformacionNacimiento_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> InformacionNacimiento_Insertar(Nullable<double> peso, Nullable<double> altura, Nullable<double> perimetroCefalico, Nullable<bool> fueCesarea, Nullable<bool> posicion, string observaciones, Nullable<bool> circularCordon, Nullable<int> iDPaciente, string motivoCesarea, string enfermedadEmbarazo, string complicacionEmbarazo, string medicacionEmbarazo, Nullable<int> edadGestacional)
        {
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(double));
    
            var alturaParameter = altura.HasValue ?
                new ObjectParameter("Altura", altura) :
                new ObjectParameter("Altura", typeof(double));
    
            var perimetroCefalicoParameter = perimetroCefalico.HasValue ?
                new ObjectParameter("PerimetroCefalico", perimetroCefalico) :
                new ObjectParameter("PerimetroCefalico", typeof(double));
    
            var fueCesareaParameter = fueCesarea.HasValue ?
                new ObjectParameter("FueCesarea", fueCesarea) :
                new ObjectParameter("FueCesarea", typeof(bool));
    
            var posicionParameter = posicion.HasValue ?
                new ObjectParameter("Posicion", posicion) :
                new ObjectParameter("Posicion", typeof(bool));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var circularCordonParameter = circularCordon.HasValue ?
                new ObjectParameter("CircularCordon", circularCordon) :
                new ObjectParameter("CircularCordon", typeof(bool));
    
            var iDPacienteParameter = iDPaciente.HasValue ?
                new ObjectParameter("IDPaciente", iDPaciente) :
                new ObjectParameter("IDPaciente", typeof(int));
    
            var motivoCesareaParameter = motivoCesarea != null ?
                new ObjectParameter("MotivoCesarea", motivoCesarea) :
                new ObjectParameter("MotivoCesarea", typeof(string));
    
            var enfermedadEmbarazoParameter = enfermedadEmbarazo != null ?
                new ObjectParameter("EnfermedadEmbarazo", enfermedadEmbarazo) :
                new ObjectParameter("EnfermedadEmbarazo", typeof(string));
    
            var complicacionEmbarazoParameter = complicacionEmbarazo != null ?
                new ObjectParameter("ComplicacionEmbarazo", complicacionEmbarazo) :
                new ObjectParameter("ComplicacionEmbarazo", typeof(string));
    
            var medicacionEmbarazoParameter = medicacionEmbarazo != null ?
                new ObjectParameter("MedicacionEmbarazo", medicacionEmbarazo) :
                new ObjectParameter("MedicacionEmbarazo", typeof(string));
    
            var edadGestacionalParameter = edadGestacional.HasValue ?
                new ObjectParameter("EdadGestacional", edadGestacional) :
                new ObjectParameter("EdadGestacional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("InformacionNacimiento_Insertar", pesoParameter, alturaParameter, perimetroCefalicoParameter, fueCesareaParameter, posicionParameter, observacionesParameter, circularCordonParameter, iDPacienteParameter, motivoCesareaParameter, enfermedadEmbarazoParameter, complicacionEmbarazoParameter, medicacionEmbarazoParameter, edadGestacionalParameter);
        }
    
        public virtual ObjectResult<string> ObtenerEdad(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ObtenerEdad", idParameter);
        }
    
        public virtual ObjectResult<string> ObtenerEdadConsulta(Nullable<int> id, Nullable<System.DateTime> fechaConsulta)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var fechaConsultaParameter = fechaConsulta.HasValue ?
                new ObjectParameter("FechaConsulta", fechaConsulta) :
                new ObjectParameter("FechaConsulta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ObtenerEdadConsulta", idParameter, fechaConsultaParameter);
        }
    
        public virtual int Paciente_Actualizar(Nullable<int> id, string nombre1, string nombre2, string apellido1, string apellido2, Nullable<System.DateTime> fechaNacimiento, Nullable<bool> nacimientoHospital, string ciudadNacimiento, string lugarNacimiento, string direccion, Nullable<int> iDGrupoSanguineo, Nullable<bool> esNino, string nombrePadre, string cedulaPadre, string nombreMadre, string cedulaMadre, string religion, string notas, string origen, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombre1Parameter = nombre1 != null ?
                new ObjectParameter("Nombre1", nombre1) :
                new ObjectParameter("Nombre1", typeof(string));
    
            var nombre2Parameter = nombre2 != null ?
                new ObjectParameter("Nombre2", nombre2) :
                new ObjectParameter("Nombre2", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var nacimientoHospitalParameter = nacimientoHospital.HasValue ?
                new ObjectParameter("NacimientoHospital", nacimientoHospital) :
                new ObjectParameter("NacimientoHospital", typeof(bool));
    
            var ciudadNacimientoParameter = ciudadNacimiento != null ?
                new ObjectParameter("CiudadNacimiento", ciudadNacimiento) :
                new ObjectParameter("CiudadNacimiento", typeof(string));
    
            var lugarNacimientoParameter = lugarNacimiento != null ?
                new ObjectParameter("LugarNacimiento", lugarNacimiento) :
                new ObjectParameter("LugarNacimiento", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var iDGrupoSanguineoParameter = iDGrupoSanguineo.HasValue ?
                new ObjectParameter("IDGrupoSanguineo", iDGrupoSanguineo) :
                new ObjectParameter("IDGrupoSanguineo", typeof(int));
    
            var esNinoParameter = esNino.HasValue ?
                new ObjectParameter("EsNino", esNino) :
                new ObjectParameter("EsNino", typeof(bool));
    
            var nombrePadreParameter = nombrePadre != null ?
                new ObjectParameter("NombrePadre", nombrePadre) :
                new ObjectParameter("NombrePadre", typeof(string));
    
            var cedulaPadreParameter = cedulaPadre != null ?
                new ObjectParameter("CedulaPadre", cedulaPadre) :
                new ObjectParameter("CedulaPadre", typeof(string));
    
            var nombreMadreParameter = nombreMadre != null ?
                new ObjectParameter("NombreMadre", nombreMadre) :
                new ObjectParameter("NombreMadre", typeof(string));
    
            var cedulaMadreParameter = cedulaMadre != null ?
                new ObjectParameter("CedulaMadre", cedulaMadre) :
                new ObjectParameter("CedulaMadre", typeof(string));
    
            var religionParameter = religion != null ?
                new ObjectParameter("Religion", religion) :
                new ObjectParameter("Religion", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Paciente_Actualizar", idParameter, nombre1Parameter, nombre2Parameter, apellido1Parameter, apellido2Parameter, fechaNacimientoParameter, nacimientoHospitalParameter, ciudadNacimientoParameter, lugarNacimientoParameter, direccionParameter, iDGrupoSanguineoParameter, esNinoParameter, nombrePadreParameter, cedulaPadreParameter, nombreMadreParameter, cedulaMadreParameter, religionParameter, notasParameter, origenParameter, activoParameter);
        }
    
        public virtual int Paciente_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Paciente_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Paciente_Insertar(string nombre1, string nombre2, string apellido1, string apellido2, Nullable<System.DateTime> fechaNacimiento, Nullable<bool> nacimientoHospital, string ciudadNacimiento, string lugarNacimiento, string direccion, Nullable<int> iDGrupoSanguineo, Nullable<bool> esNino, string nombrePadre, string cedulaPadre, string nombreMadre, string cedulaMadre, string religion, string origen, Nullable<bool> activo, string notas)
        {
            var nombre1Parameter = nombre1 != null ?
                new ObjectParameter("Nombre1", nombre1) :
                new ObjectParameter("Nombre1", typeof(string));
    
            var nombre2Parameter = nombre2 != null ?
                new ObjectParameter("Nombre2", nombre2) :
                new ObjectParameter("Nombre2", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var nacimientoHospitalParameter = nacimientoHospital.HasValue ?
                new ObjectParameter("NacimientoHospital", nacimientoHospital) :
                new ObjectParameter("NacimientoHospital", typeof(bool));
    
            var ciudadNacimientoParameter = ciudadNacimiento != null ?
                new ObjectParameter("CiudadNacimiento", ciudadNacimiento) :
                new ObjectParameter("CiudadNacimiento", typeof(string));
    
            var lugarNacimientoParameter = lugarNacimiento != null ?
                new ObjectParameter("LugarNacimiento", lugarNacimiento) :
                new ObjectParameter("LugarNacimiento", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var iDGrupoSanguineoParameter = iDGrupoSanguineo.HasValue ?
                new ObjectParameter("IDGrupoSanguineo", iDGrupoSanguineo) :
                new ObjectParameter("IDGrupoSanguineo", typeof(int));
    
            var esNinoParameter = esNino.HasValue ?
                new ObjectParameter("EsNino", esNino) :
                new ObjectParameter("EsNino", typeof(bool));
    
            var nombrePadreParameter = nombrePadre != null ?
                new ObjectParameter("NombrePadre", nombrePadre) :
                new ObjectParameter("NombrePadre", typeof(string));
    
            var cedulaPadreParameter = cedulaPadre != null ?
                new ObjectParameter("CedulaPadre", cedulaPadre) :
                new ObjectParameter("CedulaPadre", typeof(string));
    
            var nombreMadreParameter = nombreMadre != null ?
                new ObjectParameter("NombreMadre", nombreMadre) :
                new ObjectParameter("NombreMadre", typeof(string));
    
            var cedulaMadreParameter = cedulaMadre != null ?
                new ObjectParameter("CedulaMadre", cedulaMadre) :
                new ObjectParameter("CedulaMadre", typeof(string));
    
            var religionParameter = religion != null ?
                new ObjectParameter("Religion", religion) :
                new ObjectParameter("Religion", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Paciente_Insertar", nombre1Parameter, nombre2Parameter, apellido1Parameter, apellido2Parameter, fechaNacimientoParameter, nacimientoHospitalParameter, ciudadNacimientoParameter, lugarNacimientoParameter, direccionParameter, iDGrupoSanguineoParameter, esNinoParameter, nombrePadreParameter, cedulaPadreParameter, nombreMadreParameter, cedulaMadreParameter, religionParameter, origenParameter, activoParameter, notasParameter);
        }
    
        public virtual int PacienteEliminarCascada(Nullable<int> idPaciente)
        {
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("IdPaciente", idPaciente) :
                new ObjectParameter("IdPaciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PacienteEliminarCascada", idPacienteParameter);
        }
    
        public virtual int Parentesco_Actualizar(Nullable<int> id, string nombre, string notas)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Parentesco_Actualizar", idParameter, nombreParameter, notasParameter);
        }
    
        public virtual int Parentesco_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Parentesco_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Parentesco_Insertar(string nombre, string notas)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Parentesco_Insertar", nombreParameter, notasParameter);
        }
    
        public virtual ObjectResult<Reporte_ConsultaXPaciente_Result> Reporte_ConsultaXPaciente(Nullable<int> iDExpediente)
        {
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporte_ConsultaXPaciente_Result>("Reporte_ConsultaXPaciente", iDExpedienteParameter);
        }
    
        public virtual ObjectResult<Reporte_SomatometriaXPaciente_Result> Reporte_SomatometriaXPaciente(Nullable<int> iDExpediente)
        {
            var iDExpedienteParameter = iDExpediente.HasValue ?
                new ObjectParameter("IDExpediente", iDExpediente) :
                new ObjectParameter("IDExpediente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporte_SomatometriaXPaciente_Result>("Reporte_SomatometriaXPaciente", iDExpedienteParameter);
        }
    
        public virtual int Somatometria_Actualizar(Nullable<int> id, Nullable<int> iDConsulta, Nullable<double> peso, Nullable<double> estatura, Nullable<double> perimetroCefalico, Nullable<double> perimetroAbdominal, Nullable<double> perimetroToracico, Nullable<int> frecuenciaCardiaca, Nullable<int> frecuenciaRespiratoria, Nullable<double> presionSistolica, Nullable<double> presionDiastolica, Nullable<double> temperatura, string exploratorio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var iDConsultaParameter = iDConsulta.HasValue ?
                new ObjectParameter("IDConsulta", iDConsulta) :
                new ObjectParameter("IDConsulta", typeof(int));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(double));
    
            var estaturaParameter = estatura.HasValue ?
                new ObjectParameter("Estatura", estatura) :
                new ObjectParameter("Estatura", typeof(double));
    
            var perimetroCefalicoParameter = perimetroCefalico.HasValue ?
                new ObjectParameter("PerimetroCefalico", perimetroCefalico) :
                new ObjectParameter("PerimetroCefalico", typeof(double));
    
            var perimetroAbdominalParameter = perimetroAbdominal.HasValue ?
                new ObjectParameter("PerimetroAbdominal", perimetroAbdominal) :
                new ObjectParameter("PerimetroAbdominal", typeof(double));
    
            var perimetroToracicoParameter = perimetroToracico.HasValue ?
                new ObjectParameter("PerimetroToracico", perimetroToracico) :
                new ObjectParameter("PerimetroToracico", typeof(double));
    
            var frecuenciaCardiacaParameter = frecuenciaCardiaca.HasValue ?
                new ObjectParameter("FrecuenciaCardiaca", frecuenciaCardiaca) :
                new ObjectParameter("FrecuenciaCardiaca", typeof(int));
    
            var frecuenciaRespiratoriaParameter = frecuenciaRespiratoria.HasValue ?
                new ObjectParameter("FrecuenciaRespiratoria", frecuenciaRespiratoria) :
                new ObjectParameter("FrecuenciaRespiratoria", typeof(int));
    
            var presionSistolicaParameter = presionSistolica.HasValue ?
                new ObjectParameter("PresionSistolica", presionSistolica) :
                new ObjectParameter("PresionSistolica", typeof(double));
    
            var presionDiastolicaParameter = presionDiastolica.HasValue ?
                new ObjectParameter("PresionDiastolica", presionDiastolica) :
                new ObjectParameter("PresionDiastolica", typeof(double));
    
            var temperaturaParameter = temperatura.HasValue ?
                new ObjectParameter("Temperatura", temperatura) :
                new ObjectParameter("Temperatura", typeof(double));
    
            var exploratorioParameter = exploratorio != null ?
                new ObjectParameter("Exploratorio", exploratorio) :
                new ObjectParameter("Exploratorio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Somatometria_Actualizar", idParameter, iDConsultaParameter, pesoParameter, estaturaParameter, perimetroCefalicoParameter, perimetroAbdominalParameter, perimetroToracicoParameter, frecuenciaCardiacaParameter, frecuenciaRespiratoriaParameter, presionSistolicaParameter, presionDiastolicaParameter, temperaturaParameter, exploratorioParameter);
        }
    
        public virtual int Somatometria_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Somatometria_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Somatometria_Insertar(Nullable<int> iDConsulta, Nullable<double> peso, Nullable<double> estatura, Nullable<double> perimetroCefalico, Nullable<double> perimetroAbdominal, Nullable<double> perimetroToracico, Nullable<int> frecuenciaCardiaca, Nullable<int> frecuenciaRespiratoria, Nullable<double> presionSistolica, Nullable<double> presionDiastolica, Nullable<double> temperatura, string exploratorio)
        {
            var iDConsultaParameter = iDConsulta.HasValue ?
                new ObjectParameter("IDConsulta", iDConsulta) :
                new ObjectParameter("IDConsulta", typeof(int));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(double));
    
            var estaturaParameter = estatura.HasValue ?
                new ObjectParameter("Estatura", estatura) :
                new ObjectParameter("Estatura", typeof(double));
    
            var perimetroCefalicoParameter = perimetroCefalico.HasValue ?
                new ObjectParameter("PerimetroCefalico", perimetroCefalico) :
                new ObjectParameter("PerimetroCefalico", typeof(double));
    
            var perimetroAbdominalParameter = perimetroAbdominal.HasValue ?
                new ObjectParameter("PerimetroAbdominal", perimetroAbdominal) :
                new ObjectParameter("PerimetroAbdominal", typeof(double));
    
            var perimetroToracicoParameter = perimetroToracico.HasValue ?
                new ObjectParameter("PerimetroToracico", perimetroToracico) :
                new ObjectParameter("PerimetroToracico", typeof(double));
    
            var frecuenciaCardiacaParameter = frecuenciaCardiaca.HasValue ?
                new ObjectParameter("FrecuenciaCardiaca", frecuenciaCardiaca) :
                new ObjectParameter("FrecuenciaCardiaca", typeof(int));
    
            var frecuenciaRespiratoriaParameter = frecuenciaRespiratoria.HasValue ?
                new ObjectParameter("FrecuenciaRespiratoria", frecuenciaRespiratoria) :
                new ObjectParameter("FrecuenciaRespiratoria", typeof(int));
    
            var presionSistolicaParameter = presionSistolica.HasValue ?
                new ObjectParameter("PresionSistolica", presionSistolica) :
                new ObjectParameter("PresionSistolica", typeof(double));
    
            var presionDiastolicaParameter = presionDiastolica.HasValue ?
                new ObjectParameter("PresionDiastolica", presionDiastolica) :
                new ObjectParameter("PresionDiastolica", typeof(double));
    
            var temperaturaParameter = temperatura.HasValue ?
                new ObjectParameter("Temperatura", temperatura) :
                new ObjectParameter("Temperatura", typeof(double));
    
            var exploratorioParameter = exploratorio != null ?
                new ObjectParameter("Exploratorio", exploratorio) :
                new ObjectParameter("Exploratorio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Somatometria_Insertar", iDConsultaParameter, pesoParameter, estaturaParameter, perimetroCefalicoParameter, perimetroAbdominalParameter, perimetroToracicoParameter, frecuenciaCardiacaParameter, frecuenciaRespiratoriaParameter, presionSistolicaParameter, presionDiastolicaParameter, temperaturaParameter, exploratorioParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Vacuna_Actualizar(Nullable<int> id, string nombre, Nullable<int> numeroDosis, string observacion, Nullable<bool> activo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var numeroDosisParameter = numeroDosis.HasValue ?
                new ObjectParameter("NumeroDosis", numeroDosis) :
                new ObjectParameter("NumeroDosis", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Vacuna_Actualizar", idParameter, nombreParameter, numeroDosisParameter, observacionParameter, activoParameter);
        }
    
        public virtual int Vacuna_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Vacuna_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Vacuna_Insertar(string nombre, Nullable<int> numeroDosis, string observacion, Nullable<bool> activo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var numeroDosisParameter = numeroDosis.HasValue ?
                new ObjectParameter("NumeroDosis", numeroDosis) :
                new ObjectParameter("NumeroDosis", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Vacuna_Insertar", nombreParameter, numeroDosisParameter, observacionParameter, activoParameter);
        }
    }
}
