//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacuna
    {
        public Vacuna()
        {
            this.DosisVacuna = new HashSet<DosisVacuna>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> NumeroDosis { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<DosisVacuna> DosisVacuna { get; set; }
    }
}
